ALTER DEFAULT PRIVILEGES IN SCHEMA public 
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO planner;

ALTER DEFAULT PRIVILEGES IN SCHEMA public 
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO planner;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PUBLIC TO planner;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA PUBLIC TO planner;
