-- Planner - add payment attributes
ALTER TABLE public.trip_plan
    ADD COLUMN plan_state character varying(2)
;

-- By definition ordinary trip plans (generated by the planner) and shout-out solutions
-- are final plans.
UPDATE public.trip_plan SET plan_state = 'FN' WHERE plan_type = 'REG' OR plan_type = 'SOS';

-- By definition all plans without a request duration are open (often expired)
UPDATE public.trip_plan SET plan_state = 'OP' WHERE request_duration is NULL;

-- If there are trips connected to the shout-out plan, than the plan was finalized.
UPDATE public.trip_plan SET plan_state = 'FN' WHERE plan_state IS NULL AND trip_plan.id IN (
SELECT p.id
	FROM public.trip_plan p
	JOIN itinerary it ON it.trip_plan = p.id
	JOIN trip t ON t.itinerary = it.id
	WHERE plan_state is NULL AND plan_type = 'SHO' AND (t.state = 'CNC' OR t.state = 'CMP')
)

-- The remaining shout-outs have been cancelled
UPDATE public.trip_plan SET plan_state = 'CN' WHERE plan_state is NULL AND plan_type = 'SHO';

ALTER TABLE public.trip_plan
    ALTER COLUMN plan_state SET NOT NULL
;
